/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_mainwin (void)
{
  GtkWidget *mainwin;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *File;
  GtkWidget *File_menu;
  GtkAccelGroup *File_menu_accels;
  GtkWidget *FileConnect;
  GtkWidget *Refresh;
  GtkWidget *separator1;
  GtkWidget *Quit;
  GtkWidget *Options;
  GtkWidget *Options_menu;
  GtkAccelGroup *Options_menu_accels;
  GtkWidget *Trails;
  GtkWidget *ID;
  GtkWidget *OpponentID;
  GtkWidget *help;
  GtkWidget *help_menu;
  GtkAccelGroup *help_menu_accels;
  GtkWidget *general_help;
  GtkWidget *about;
  GtkWidget *toolbar;
  GtkWidget *button51;
  GtkWidget *pixmap13;
  GtkWidget *stepback_button;
  GtkWidget *pixmap2;
  GtkWidget *pause_button;
  GtkWidget *pixmap3;
  GtkWidget *button50;
  GtkWidget *pixmap12;
  GtkWidget *play_button;
  GtkWidget *pixmap4;
  GtkWidget *stepforward_button;
  GtkWidget *pixmap5;
  GtkWidget *button52;
  GtkWidget *pixmap14;
  GtkWidget *label2;
  GtkWidget *tacticcombo;
  GList *tacticcombo_items = NULL;
  GtkWidget *tactic_ctrl;
  GtkWidget *param_ctrl;
  GtkWidget *applytactic_button;
  GtkWidget *pixmap7;
  GtkWidget *stoptactic_button;
  GtkWidget *pixmap8;
  GtkWidget *gameinfo_button;
  GtkWidget *pixmap1;
  GtkWidget *button1;
  GtkWidget *pixmap6;
  GtkWidget *button18;
  GtkWidget *pixmap9;
  GtkWidget *button19;
  GtkWidget *pixmap10;
  GtkWidget *button49;
  GtkWidget *pixmap11;
  GtkWidget *toolbar1;
  GtkWidget *label26;
  GtkWidget *checkbutton2;
  GtkWidget *checkbutton3;
  GtkWidget *checkbutton4;
  GtkWidget *checkbutton5;
  GtkWidget *checkbutton6;
  GtkWidget *checkbutton7;
  GtkWidget *hbox1;
  GtkWidget *aspectframe;
  GtkWidget *darea;
  GtkWidget *gameinfo;
  GtkWidget *label8;
  GtkWidget *hbox2;
  GtkWidget *label7;
  GtkWidget *gameinfo_entry;
  GtkWidget *hbox3;
  GtkWidget *label6;
  GtkWidget *ballinfo_entry;
  GtkWidget *label4;
  GtkWidget *scrolledwindow2;
  GtkWidget *statsinfo_entry;
  GtkWidget *SetCtrlBox;
  GtkWidget *label9;
  GtkWidget *label16;
  GtkWidget *table1;
  GtkWidget *blue_robot0;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *blue_robot1;
  GtkWidget *blue_robot2;
  GtkWidget *blue_robot3;
  GtkWidget *blue_robot4;
  GtkWidget *blue_robot8;
  GtkWidget *blue_robot7;
  GtkWidget *blue_robot6;
  GtkWidget *blue_robot5;
  GtkWidget *blue_robot9;
  GtkWidget *enable_blue_covers;
  GtkWidget *enable_blue;
  GtkWidget *label11;
  GtkWidget *table2;
  GtkWidget *yellow_robot0;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *yellow_robot1;
  GtkWidget *yellow_robot2;
  GtkWidget *yellow_robot3;
  GtkWidget *yellow_robot4;
  GtkWidget *yellow_robot8;
  GtkWidget *yellow_robot7;
  GtkWidget *yellow_robot6;
  GtkWidget *yellow_robot5;
  GtkWidget *yellow_robot9;
  GtkWidget *enable_yellow_covers;
  GtkWidget *enable_yellow;
  GtkWidget *button3;
  GtkWidget *GraphCtrl;
  GtkWidget *label27;
  GtkWidget *vbox9;
  GtkWidget *label52;
  GtkWidget *hbox18;
  GtkWidget *label47;
  GtkWidget *button45;
  GtkWidget *hbox19;
  GtkWidget *label48;
  GtkWidget *button46;
  GtkWidget *vbox7;
  GtkWidget *label53;
  GtkWidget *hbox4;
  GtkWidget *label28;
  GtkWidget *button22;
  GtkWidget *hbox5;
  GtkWidget *label29;
  GtkWidget *button23;
  GtkWidget *hbox6;
  GtkWidget *label30;
  GtkWidget *button24;
  GtkWidget *hbox7;
  GtkWidget *label31;
  GtkWidget *button40;
  GtkWidget *hbox8;
  GtkWidget *label32;
  GtkWidget *button26;
  GtkWidget *vbox8;
  GtkWidget *label40;
  GtkWidget *hbox13;
  GtkWidget *label41;
  GtkWidget *button31;
  GtkWidget *hbox14;
  GtkWidget *label42;
  GtkWidget *button41;
  GtkWidget *hbox15;
  GtkWidget *label43;
  GtkWidget *button42;
  GtkWidget *hbox16;
  GtkWidget *label44;
  GtkWidget *button43;
  GtkWidget *hbox17;
  GtkWidget *label45;
  GtkWidget *button44;
  GtkWidget *statusbar;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  mainwin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (mainwin), "mainwin", mainwin);
  gtk_widget_set_events (mainwin, GDK_KEY_PRESS_MASK);
  gtk_window_set_title (GTK_WINDOW (mainwin), "CM Dragons'02");

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwin), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  File = gtk_menu_item_new_with_label ("File");
  gtk_widget_ref (File);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "File", File,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (File);
  gtk_container_add (GTK_CONTAINER (menubar1), File);

  File_menu = gtk_menu_new ();
  gtk_widget_ref (File_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "File_menu", File_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (File), File_menu);
  File_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (File_menu));

  FileConnect = gtk_menu_item_new_with_label ("Connect");
  gtk_widget_ref (FileConnect);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "FileConnect", FileConnect,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (FileConnect);
  gtk_container_add (GTK_CONTAINER (File_menu), FileConnect);
  gtk_tooltips_set_tip (tooltips, FileConnect, "Connect to server", NULL);
  gtk_widget_add_accelerator (FileConnect, "activate", accel_group,
                              GDK_C, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  Refresh = gtk_menu_item_new_with_label ("Refresh");
  gtk_widget_ref (Refresh);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "Refresh", Refresh,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Refresh);
  gtk_container_add (GTK_CONTAINER (File_menu), Refresh);
  gtk_tooltips_set_tip (tooltips, Refresh, "Refresh the display", NULL);
  gtk_widget_add_accelerator (Refresh, "activate", accel_group,
                              GDK_R, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  separator1 = gtk_menu_item_new ();
  gtk_widget_ref (separator1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "separator1", separator1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (separator1);
  gtk_container_add (GTK_CONTAINER (File_menu), separator1);
  gtk_widget_set_sensitive (separator1, FALSE);

  Quit = gtk_menu_item_new_with_label ("Quit");
  gtk_widget_ref (Quit);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "Quit", Quit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Quit);
  gtk_container_add (GTK_CONTAINER (File_menu), Quit);
  gtk_tooltips_set_tip (tooltips, Quit, "Quit the program", NULL);
  gtk_widget_add_accelerator (Quit, "activate", accel_group,
                              GDK_Q, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);

  Options = gtk_menu_item_new_with_label ("Options");
  gtk_widget_ref (Options);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "Options", Options,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Options);
  gtk_container_add (GTK_CONTAINER (menubar1), Options);
  gtk_tooltips_set_tip (tooltips, Options, "Change options settings", NULL);

  Options_menu = gtk_menu_new ();
  gtk_widget_ref (Options_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "Options_menu", Options_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (Options), Options_menu);
  Options_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (Options_menu));

  Trails = gtk_check_menu_item_new_with_label ("Trails");
  gtk_widget_ref (Trails);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "Trails", Trails,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (Trails);
  gtk_container_add (GTK_CONTAINER (Options_menu), Trails);
  gtk_tooltips_set_tip (tooltips, Trails, "Show object trails", NULL);
  gtk_widget_add_accelerator (Trails, "activate", accel_group,
                              GDK_T, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (Trails), TRUE);

  ID = gtk_check_menu_item_new_with_label ("ID's");
  gtk_widget_ref (ID);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "ID", ID,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ID);
  gtk_container_add (GTK_CONTAINER (Options_menu), ID);
  gtk_tooltips_set_tip (tooltips, ID, "Show ID's", NULL);
  gtk_widget_add_accelerator (ID, "activate", accel_group,
                              GDK_I, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (ID), TRUE);

  OpponentID = gtk_check_menu_item_new_with_label ("Opponent ID's");
  gtk_widget_ref (OpponentID);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "OpponentID", OpponentID,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (OpponentID);
  gtk_container_add (GTK_CONTAINER (Options_menu), OpponentID);
  gtk_tooltips_set_tip (tooltips, OpponentID, "Show opponent ID's", NULL);
  gtk_widget_add_accelerator (OpponentID, "activate", accel_group,
                              GDK_O, GDK_MOD1_MASK,
                              GTK_ACCEL_VISIBLE);
  gtk_check_menu_item_set_show_toggle (GTK_CHECK_MENU_ITEM (OpponentID), TRUE);

  help = gtk_menu_item_new_with_label ("Help");
  gtk_widget_ref (help);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "help", help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help);
  gtk_container_add (GTK_CONTAINER (menubar1), help);
  gtk_tooltips_set_tip (tooltips, help, "Press for help...what else do you think it's for?", NULL);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help));

  help_menu = gtk_menu_new ();
  gtk_widget_ref (help_menu);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "help_menu", help_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help), help_menu);
  help_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help_menu));

  general_help = gtk_menu_item_new_with_label ("General help...");
  gtk_widget_ref (general_help);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "general_help", general_help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (general_help);
  gtk_container_add (GTK_CONTAINER (help_menu), general_help);
  gtk_tooltips_set_tip (tooltips, general_help, "select for general help", NULL);

  about = gtk_menu_item_new_with_label ("About");
  gtk_widget_ref (about);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "about", about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (help_menu), about);

  toolbar = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "toolbar", toolbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar, FALSE, FALSE, 0);
  gtk_toolbar_set_space_size (GTK_TOOLBAR (toolbar), 20);

  button51 = gtk_button_new ();
  gtk_widget_ref (button51);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button51", button51,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button51);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), button51, NULL, NULL);

  pixmap13 = create_pixmap (mainwin, "rwnd.xpm");
  gtk_widget_ref (pixmap13);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap13", pixmap13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap13);
  gtk_container_add (GTK_CONTAINER (button51), pixmap13);

  stepback_button = gtk_button_new ();
  gtk_widget_ref (stepback_button);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "stepback_button", stepback_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (stepback_button);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), stepback_button, NULL, NULL);

  pixmap2 = create_pixmap (mainwin, "stepback.xpm");
  gtk_widget_ref (pixmap2);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap2", pixmap2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap2);
  gtk_container_add (GTK_CONTAINER (stepback_button), pixmap2);

  pause_button = gtk_button_new ();
  gtk_widget_ref (pause_button);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pause_button", pause_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pause_button);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), pause_button, NULL, NULL);

  pixmap3 = create_pixmap (mainwin, "pause.xpm");
  gtk_widget_ref (pixmap3);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap3", pixmap3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap3);
  gtk_container_add (GTK_CONTAINER (pause_button), pixmap3);

  button50 = gtk_button_new ();
  gtk_widget_ref (button50);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button50", button50,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button50);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), button50, NULL, NULL);

  pixmap12 = create_pixmap (mainwin, "playback.xpm");
  gtk_widget_ref (pixmap12);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap12", pixmap12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap12);
  gtk_container_add (GTK_CONTAINER (button50), pixmap12);

  play_button = gtk_button_new ();
  gtk_widget_ref (play_button);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "play_button", play_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (play_button);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), play_button, NULL, NULL);

  pixmap4 = create_pixmap (mainwin, "play.xpm");
  gtk_widget_ref (pixmap4);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap4", pixmap4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap4);
  gtk_container_add (GTK_CONTAINER (play_button), pixmap4);

  stepforward_button = gtk_button_new ();
  gtk_widget_ref (stepforward_button);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "stepforward_button", stepforward_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (stepforward_button);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), stepforward_button, NULL, NULL);

  pixmap5 = create_pixmap (mainwin, "step.xpm");
  gtk_widget_ref (pixmap5);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap5", pixmap5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap5);
  gtk_container_add (GTK_CONTAINER (stepforward_button), pixmap5);

  button52 = gtk_button_new ();
  gtk_widget_ref (button52);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button52", button52,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button52);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), button52, NULL, NULL);

  pixmap14 = create_pixmap (mainwin, "ffwd.xpm");
  gtk_widget_ref (pixmap14);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap14", pixmap14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap14);
  gtk_container_add (GTK_CONTAINER (button52), pixmap14);

  label2 = gtk_label_new ("Tactic");
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), label2, NULL, NULL);
  gtk_misc_set_padding (GTK_MISC (label2), 5, 0);

  tacticcombo = gtk_combo_new ();
  gtk_widget_ref (tacticcombo);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "tacticcombo", tacticcombo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tacticcombo);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), tacticcombo, NULL, NULL);
  gtk_widget_set_usize (tacticcombo, 109, -2);
  tacticcombo_items = g_list_append (tacticcombo_items, (gpointer) "");
  gtk_combo_set_popdown_strings (GTK_COMBO (tacticcombo), tacticcombo_items);
  g_list_free (tacticcombo_items);

  tactic_ctrl = GTK_COMBO (tacticcombo)->entry;
  gtk_widget_ref (tactic_ctrl);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "tactic_ctrl", tactic_ctrl,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tactic_ctrl);
  gtk_tooltips_set_tip (tooltips, tactic_ctrl, "Select the tactic to run for the selected robot", NULL);
  gtk_entry_set_editable (GTK_ENTRY (tactic_ctrl), FALSE);

  param_ctrl = gtk_entry_new ();
  gtk_widget_ref (param_ctrl);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "param_ctrl", param_ctrl,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (param_ctrl);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), param_ctrl, "Add parameters for the selected tactic", NULL);
  gtk_widget_set_usize (param_ctrl, 91, -2);

  applytactic_button = gtk_button_new ();
  gtk_widget_ref (applytactic_button);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "applytactic_button", applytactic_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (applytactic_button);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), applytactic_button, NULL, NULL);

  pixmap7 = create_pixmap (mainwin, "apply_tactic.xpm");
  gtk_widget_ref (pixmap7);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap7", pixmap7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap7);
  gtk_container_add (GTK_CONTAINER (applytactic_button), pixmap7);

  stoptactic_button = gtk_button_new ();
  gtk_widget_ref (stoptactic_button);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "stoptactic_button", stoptactic_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (stoptactic_button);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), stoptactic_button, NULL, NULL);

  pixmap8 = create_pixmap (mainwin, "stop_tactic.xpm");
  gtk_widget_ref (pixmap8);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap8", pixmap8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap8);
  gtk_container_add (GTK_CONTAINER (stoptactic_button), pixmap8);

  gameinfo_button = gtk_button_new ();
  gtk_widget_ref (gameinfo_button);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "gameinfo_button", gameinfo_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gameinfo_button);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), gameinfo_button, NULL, NULL);

  pixmap1 = create_pixmap (mainwin, "show.xpm");
  gtk_widget_ref (pixmap1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap1", pixmap1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap1);
  gtk_container_add (GTK_CONTAINER (gameinfo_button), pixmap1);

  button1 = gtk_button_new ();
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), button1, NULL, NULL);

  pixmap6 = create_pixmap (mainwin, "set.xpm");
  gtk_widget_ref (pixmap6);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap6", pixmap6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap6);
  gtk_container_add (GTK_CONTAINER (button1), pixmap6);

  button18 = gtk_button_new ();
  gtk_widget_ref (button18);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button18", button18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button18);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), button18, NULL, NULL);

  pixmap9 = create_pixmap (mainwin, "refbox.xpm");
  gtk_widget_ref (pixmap9);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap9", pixmap9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap9);
  gtk_container_add (GTK_CONTAINER (button18), pixmap9);

  button19 = gtk_button_new ();
  gtk_widget_ref (button19);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button19", button19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button19);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), button19, NULL, NULL);

  pixmap10 = create_pixmap (mainwin, "drive.xpm");
  gtk_widget_ref (pixmap10);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap10", pixmap10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap10);
  gtk_container_add (GTK_CONTAINER (button19), pixmap10);

  button49 = gtk_button_new ();
  gtk_widget_ref (button49);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button49", button49,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button49);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar), button49, NULL, NULL);

  pixmap11 = create_pixmap (mainwin, "graph.xpm");
  gtk_widget_ref (pixmap11);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "pixmap11", pixmap11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pixmap11);
  gtk_container_add (GTK_CONTAINER (button49), pixmap11);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);

  label26 = gtk_label_new ("Debug Controls:");
  gtk_widget_ref (label26);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label26", label26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label26);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), label26, NULL, NULL);

  checkbutton2 = gtk_check_button_new_with_label ("Vision");
  gtk_widget_ref (checkbutton2);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "checkbutton2", checkbutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton2);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), checkbutton2, NULL, NULL);

  checkbutton3 = gtk_check_button_new_with_label ("Tracker");
  gtk_widget_ref (checkbutton3);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "checkbutton3", checkbutton3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton3);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), checkbutton3, NULL, NULL);

  checkbutton4 = gtk_check_button_new_with_label ("Motion");
  gtk_widget_ref (checkbutton4);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "checkbutton4", checkbutton4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton4);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), checkbutton4, NULL, NULL);

  checkbutton5 = gtk_check_button_new_with_label ("Navigation");
  gtk_widget_ref (checkbutton5);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "checkbutton5", checkbutton5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton5);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), checkbutton5, NULL, NULL);

  checkbutton6 = gtk_check_button_new_with_label ("Tactic");
  gtk_widget_ref (checkbutton6);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "checkbutton6", checkbutton6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton6);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), checkbutton6, NULL, NULL);

  checkbutton7 = gtk_check_button_new_with_label ("Strategy");
  gtk_widget_ref (checkbutton7);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "checkbutton7", checkbutton7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkbutton7);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), checkbutton7, NULL, NULL);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  aspectframe = gtk_aspect_frame_new (NULL, 0.5, 0.5, 0.5, TRUE);
  gtk_widget_ref (aspectframe);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "aspectframe", aspectframe,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (aspectframe);
  gtk_box_pack_start (GTK_BOX (hbox1), aspectframe, TRUE, TRUE, 0);

  darea = gtk_drawing_area_new ();
  gtk_widget_ref (darea);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "darea", darea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (darea);
  gtk_container_add (GTK_CONTAINER (aspectframe), darea);
  gtk_widget_set_usize (darea, 405, 444);
  GTK_WIDGET_SET_FLAGS (darea, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (darea, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, darea, "left mouse button to move objects, right button to orient robots, right button to give ball velocity, middle button to give goto command", NULL);
  gtk_widget_set_events (darea, GDK_POINTER_MOTION_MASK | GDK_BUTTON1_MOTION_MASK | GDK_BUTTON2_MOTION_MASK | GDK_BUTTON3_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK | GDK_PROXIMITY_IN_MASK | GDK_PROXIMITY_OUT_MASK);

  gameinfo = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (gameinfo);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "gameinfo", gameinfo,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (hbox1), gameinfo, TRUE, TRUE, 0);

  label8 = gtk_label_new ("Game Information");
  gtk_widget_ref (label8);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label8", label8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (gameinfo), label8, FALSE, FALSE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (gameinfo), hbox2, FALSE, FALSE, 0);

  label7 = gtk_label_new ("Game Info");
  gtk_widget_ref (label7);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label7", label7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox2), label7, FALSE, FALSE, 0);
  gtk_widget_set_usize (label7, 66, -2);
  gtk_misc_set_padding (GTK_MISC (label7), 5, 0);

  gameinfo_entry = gtk_entry_new ();
  gtk_widget_ref (gameinfo_entry);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "gameinfo_entry", gameinfo_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gameinfo_entry);
  gtk_box_pack_start (GTK_BOX (hbox2), gameinfo_entry, TRUE, TRUE, 0);
  gtk_entry_set_editable (GTK_ENTRY (gameinfo_entry), FALSE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (gameinfo), hbox3, FALSE, FALSE, 0);

  label6 = gtk_label_new ("Ball Info");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox3), label6, FALSE, FALSE, 0);
  gtk_widget_set_usize (label6, 66, -2);
  gtk_misc_set_padding (GTK_MISC (label6), 5, 0);

  ballinfo_entry = gtk_entry_new ();
  gtk_widget_ref (ballinfo_entry);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "ballinfo_entry", ballinfo_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ballinfo_entry);
  gtk_box_pack_start (GTK_BOX (hbox3), ballinfo_entry, TRUE, TRUE, 0);
  gtk_entry_set_editable (GTK_ENTRY (ballinfo_entry), FALSE);

  label4 = gtk_label_new ("Stats Info");
  gtk_widget_ref (label4);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label4", label4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (gameinfo), label4, FALSE, FALSE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (gameinfo), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_NEVER);

  statsinfo_entry = gtk_text_new (NULL, NULL);
  gtk_widget_ref (statsinfo_entry);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "statsinfo_entry", statsinfo_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statsinfo_entry);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), statsinfo_entry);

  SetCtrlBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (SetCtrlBox);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "SetCtrlBox", SetCtrlBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (hbox1), SetCtrlBox, FALSE, FALSE, 0);

  label9 = gtk_label_new ("Enable Control");
  gtk_widget_ref (label9);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label9", label9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), label9, FALSE, FALSE, 0);

  label16 = gtk_label_new ("Blue Team");
  gtk_widget_ref (label16);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label16", label16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), label16, FALSE, FALSE, 0);

  table1 = gtk_table_new (6, 2, FALSE);
  gtk_widget_ref (table1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "table1", table1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table1);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), table1, FALSE, FALSE, 0);

  blue_robot0 = gtk_check_button_new_with_label ("0");
  gtk_widget_ref (blue_robot0);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot0", blue_robot0,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot0);
  gtk_table_attach (GTK_TABLE (table1), blue_robot0, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label12 = gtk_label_new ("DiffBot");
  gtk_widget_ref (label12);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label12", label12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table1), label12, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label12), 4, 0);

  label13 = gtk_label_new ("OmniBot");
  gtk_widget_ref (label13);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label13", label13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table1), label13, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label13), 4, 0);

  blue_robot1 = gtk_check_button_new_with_label ("1");
  gtk_widget_ref (blue_robot1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot1", blue_robot1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot1);
  gtk_table_attach (GTK_TABLE (table1), blue_robot1, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  blue_robot2 = gtk_check_button_new_with_label ("2");
  gtk_widget_ref (blue_robot2);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot2", blue_robot2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot2);
  gtk_table_attach (GTK_TABLE (table1), blue_robot2, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  blue_robot3 = gtk_check_button_new_with_label ("3");
  gtk_widget_ref (blue_robot3);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot3", blue_robot3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot3);
  gtk_table_attach (GTK_TABLE (table1), blue_robot3, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  blue_robot4 = gtk_check_button_new_with_label ("4");
  gtk_widget_ref (blue_robot4);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot4", blue_robot4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot4);
  gtk_table_attach (GTK_TABLE (table1), blue_robot4, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  blue_robot8 = gtk_check_button_new_with_label ("8");
  gtk_widget_ref (blue_robot8);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot8", blue_robot8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot8);
  gtk_table_attach (GTK_TABLE (table1), blue_robot8, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  blue_robot7 = gtk_check_button_new_with_label ("7");
  gtk_widget_ref (blue_robot7);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot7", blue_robot7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot7);
  gtk_table_attach (GTK_TABLE (table1), blue_robot7, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  blue_robot6 = gtk_check_button_new_with_label ("6");
  gtk_widget_ref (blue_robot6);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot6", blue_robot6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot6);
  gtk_table_attach (GTK_TABLE (table1), blue_robot6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  blue_robot5 = gtk_check_button_new_with_label ("5");
  gtk_widget_ref (blue_robot5);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot5", blue_robot5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot5);
  gtk_table_attach (GTK_TABLE (table1), blue_robot5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  blue_robot9 = gtk_check_button_new_with_label ("9");
  gtk_widget_ref (blue_robot9);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "blue_robot9", blue_robot9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (blue_robot9);
  gtk_table_attach (GTK_TABLE (table1), blue_robot9, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  enable_blue_covers = gtk_check_button_new_with_label ("Covers");
  gtk_widget_ref (enable_blue_covers);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "enable_blue_covers", enable_blue_covers,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (enable_blue_covers);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), enable_blue_covers, FALSE, FALSE, 0);

  enable_blue = gtk_check_button_new_with_label ("Enable");
  gtk_widget_ref (enable_blue);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "enable_blue", enable_blue,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (enable_blue);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), enable_blue, FALSE, FALSE, 0);

  label11 = gtk_label_new ("Yellow Team");
  gtk_widget_ref (label11);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label11", label11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), label11, FALSE, FALSE, 0);

  table2 = gtk_table_new (6, 2, FALSE);
  gtk_widget_ref (table2);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "table2", table2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table2);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), table2, FALSE, FALSE, 0);

  yellow_robot0 = gtk_check_button_new_with_label ("0");
  gtk_widget_ref (yellow_robot0);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot0", yellow_robot0,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot0);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot0, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label14 = gtk_label_new ("DiffBot");
  gtk_widget_ref (label14);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label14", label14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label14), 4, 0);

  label15 = gtk_label_new ("OmniBot");
  gtk_widget_ref (label15);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label15", label15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table2), label15, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label15), 4, 0);

  yellow_robot1 = gtk_check_button_new_with_label ("1");
  gtk_widget_ref (yellow_robot1);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot1", yellow_robot1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot1);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot1, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  yellow_robot2 = gtk_check_button_new_with_label ("2");
  gtk_widget_ref (yellow_robot2);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot2", yellow_robot2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot2);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot2, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  yellow_robot3 = gtk_check_button_new_with_label ("3");
  gtk_widget_ref (yellow_robot3);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot3", yellow_robot3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot3);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot3, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  yellow_robot4 = gtk_check_button_new_with_label ("4");
  gtk_widget_ref (yellow_robot4);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot4", yellow_robot4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot4);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot4, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  yellow_robot8 = gtk_check_button_new_with_label ("8");
  gtk_widget_ref (yellow_robot8);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot8", yellow_robot8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot8);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot8, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  yellow_robot7 = gtk_check_button_new_with_label ("7");
  gtk_widget_ref (yellow_robot7);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot7", yellow_robot7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot7);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot7, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  yellow_robot6 = gtk_check_button_new_with_label ("6");
  gtk_widget_ref (yellow_robot6);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot6", yellow_robot6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot6);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot6, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  yellow_robot5 = gtk_check_button_new_with_label ("5");
  gtk_widget_ref (yellow_robot5);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot5", yellow_robot5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot5);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot5, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  yellow_robot9 = gtk_check_button_new_with_label ("9");
  gtk_widget_ref (yellow_robot9);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "yellow_robot9", yellow_robot9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (yellow_robot9);
  gtk_table_attach (GTK_TABLE (table2), yellow_robot9, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  enable_yellow_covers = gtk_check_button_new_with_label ("Covers");
  gtk_widget_ref (enable_yellow_covers);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "enable_yellow_covers", enable_yellow_covers,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (enable_yellow_covers);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), enable_yellow_covers, FALSE, FALSE, 4);

  enable_yellow = gtk_check_button_new_with_label ("Enable");
  gtk_widget_ref (enable_yellow);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "enable_yellow", enable_yellow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (enable_yellow);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), enable_yellow, FALSE, FALSE, 0);

  button3 = gtk_button_new_with_label ("Set");
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  gtk_box_pack_start (GTK_BOX (SetCtrlBox), button3, FALSE, FALSE, 0);

  GraphCtrl = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (GraphCtrl);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "GraphCtrl", GraphCtrl,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_box_pack_start (GTK_BOX (hbox1), GraphCtrl, FALSE, FALSE, 0);

  label27 = gtk_label_new ("Graph Control");
  gtk_widget_ref (label27);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label27", label27,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (GraphCtrl), label27, FALSE, FALSE, 0);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (GraphCtrl), vbox9, TRUE, TRUE, 0);

  label52 = gtk_label_new ("Ball");
  gtk_widget_ref (label52);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label52", label52,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (vbox9), label52, TRUE, TRUE, 0);

  hbox18 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox18);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox18", hbox18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox18, TRUE, TRUE, 0);

  label47 = gtk_label_new ("Position");
  gtk_widget_ref (label47);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label47", label47,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label47);
  gtk_box_pack_start (GTK_BOX (hbox18), label47, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label47), 11, 0);

  button45 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button45);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button45", button45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button45);
  gtk_box_pack_start (GTK_BOX (hbox18), button45, FALSE, FALSE, 0);

  hbox19 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox19);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox19", hbox19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox19);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox19, TRUE, TRUE, 0);

  label48 = gtk_label_new ("Velocity");
  gtk_widget_ref (label48);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label48", label48,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label48);
  gtk_box_pack_start (GTK_BOX (hbox19), label48, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label48), 11, 0);

  button46 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button46);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button46", button46,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button46);
  gtk_box_pack_start (GTK_BOX (hbox19), button46, FALSE, FALSE, 0);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (GraphCtrl), vbox7, TRUE, TRUE, 0);

  label53 = gtk_label_new ("Blue Team");
  gtk_widget_ref (label53);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label53", label53,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label53);
  gtk_box_pack_start (GTK_BOX (vbox7), label53, TRUE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox4, TRUE, TRUE, 0);

  label28 = gtk_label_new ("Position");
  gtk_widget_ref (label28);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label28", label28,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox4), label28, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label28), 11, 0);

  button22 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button22);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button22", button22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button22);
  gtk_box_pack_start (GTK_BOX (hbox4), button22, FALSE, FALSE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox5, TRUE, TRUE, 0);

  label29 = gtk_label_new ("Velocity");
  gtk_widget_ref (label29);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label29", label29,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox5), label29, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label29), 11, 0);

  button23 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button23);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button23", button23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button23);
  gtk_box_pack_start (GTK_BOX (hbox5), button23, FALSE, FALSE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox6, TRUE, TRUE, 0);

  label30 = gtk_label_new ("Acc");
  gtk_widget_ref (label30);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label30", label30,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox6), label30, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label30), 11, 0);

  button24 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button24);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button24", button24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button24);
  gtk_box_pack_start (GTK_BOX (hbox6), button24, FALSE, FALSE, 0);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox7);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox7", hbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox7, TRUE, TRUE, 0);

  label31 = gtk_label_new ("Near Ball");
  gtk_widget_ref (label31);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label31", label31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox7), label31, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label31), 11, 0);

  button40 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button40);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button40", button40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button40);
  gtk_box_pack_start (GTK_BOX (hbox7), button40, FALSE, FALSE, 0);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox7), hbox8, TRUE, TRUE, 0);

  label32 = gtk_label_new ("Shoot");
  gtk_widget_ref (label32);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label32", label32,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox8), label32, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label32), 11, 0);

  button26 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button26);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button26", button26,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button26);
  gtk_box_pack_start (GTK_BOX (hbox8), button26, FALSE, FALSE, 0);

  vbox8 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (GraphCtrl), vbox8, TRUE, TRUE, 0);

  label40 = gtk_label_new ("Yellow Team");
  gtk_widget_ref (label40);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label40", label40,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (vbox8), label40, TRUE, TRUE, 0);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox13);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox13", hbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox13, TRUE, TRUE, 0);

  label41 = gtk_label_new ("Position");
  gtk_widget_ref (label41);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label41", label41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox13), label41, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label41), 11, 0);

  button31 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button31);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button31", button31,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button31);
  gtk_box_pack_start (GTK_BOX (hbox13), button31, FALSE, FALSE, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox14);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox14", hbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox14, TRUE, TRUE, 0);

  label42 = gtk_label_new ("Velocity");
  gtk_widget_ref (label42);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label42", label42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label42);
  gtk_box_pack_start (GTK_BOX (hbox14), label42, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label42), 11, 0);

  button41 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button41);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button41", button41,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button41);
  gtk_box_pack_start (GTK_BOX (hbox14), button41, FALSE, FALSE, 0);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox15);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox15", hbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox15, TRUE, TRUE, 0);

  label43 = gtk_label_new ("Acc");
  gtk_widget_ref (label43);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label43", label43,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox15), label43, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label43), 11, 0);

  button42 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button42);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button42", button42,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button42);
  gtk_box_pack_start (GTK_BOX (hbox15), button42, FALSE, FALSE, 0);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox16);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox16", hbox16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox16, TRUE, TRUE, 0);

  label44 = gtk_label_new ("Near Ball");
  gtk_widget_ref (label44);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label44", label44,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox16), label44, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label44), 11, 0);

  button43 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button43);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button43", button43,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button43);
  gtk_box_pack_start (GTK_BOX (hbox16), button43, FALSE, FALSE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox17);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "hbox17", hbox17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox17, TRUE, TRUE, 0);

  label45 = gtk_label_new ("Shoot");
  gtk_widget_ref (label45);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "label45", label45,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox17), label45, TRUE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (label45), 11, 0);

  button44 = gtk_button_new_with_label ("Show");
  gtk_widget_ref (button44);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "button44", button44,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button44);
  gtk_box_pack_start (GTK_BOX (hbox17), button44, FALSE, FALSE, 0);

  statusbar = gtk_statusbar_new ();
  gtk_widget_ref (statusbar);
  gtk_object_set_data_full (GTK_OBJECT (mainwin), "statusbar", statusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (mainwin), "destroy",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (mainwin), "key_press_event",
                      GTK_SIGNAL_FUNC (on_darea_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (File), "activate",
                      GTK_SIGNAL_FUNC (OnFileActivate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (FileConnect), "activate",
                      GTK_SIGNAL_FUNC (on_FileConnect_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Refresh), "activate",
                      GTK_SIGNAL_FUNC (on_Refresh_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Quit), "activate",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (Trails), "activate",
                      GTK_SIGNAL_FUNC (on_Trails_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ID), "activate",
                      GTK_SIGNAL_FUNC (on_ID_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (OpponentID), "activate",
                      GTK_SIGNAL_FUNC (on_OpponentID_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (general_help), "activate",
                      GTK_SIGNAL_FUNC (on_general_help_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about), "activate",
                      GTK_SIGNAL_FUNC (on_about_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button51), "clicked",
                      GTK_SIGNAL_FUNC (on_vcr_clicked),
                      GINT_TO_POINTER(VCR_RWND));
  gtk_signal_connect (GTK_OBJECT (stepback_button), "clicked",
                      GTK_SIGNAL_FUNC (on_vcr_clicked),
                      GINT_TO_POINTER(VCR_STEPBACK));
  gtk_signal_connect (GTK_OBJECT (pause_button), "clicked",
                      GTK_SIGNAL_FUNC (on_vcr_clicked),
                      GINT_TO_POINTER(VCR_PAUSE));
  gtk_signal_connect (GTK_OBJECT (button50), "clicked",
                      GTK_SIGNAL_FUNC (on_vcr_clicked),
                      GINT_TO_POINTER(VCR_PLAYBACK));
  gtk_signal_connect (GTK_OBJECT (play_button), "clicked",
                      GTK_SIGNAL_FUNC (on_vcr_clicked),
                      GINT_TO_POINTER(VCR_PLAY));
  gtk_signal_connect (GTK_OBJECT (stepforward_button), "clicked",
                      GTK_SIGNAL_FUNC (on_vcr_clicked),
                      GINT_TO_POINTER(VCR_STEP));
  gtk_signal_connect (GTK_OBJECT (button52), "clicked",
                      GTK_SIGNAL_FUNC (on_vcr_clicked),
                      GINT_TO_POINTER(VCR_FFWD));
  gtk_signal_connect (GTK_OBJECT (tactic_ctrl), "changed",
                      GTK_SIGNAL_FUNC (on_tactic_ctrl_changed),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (param_ctrl), "activate",
                      GTK_SIGNAL_FUNC (on_param_ctrl_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (applytactic_button), "clicked",
                      GTK_SIGNAL_FUNC (on_tactic_button_clicked),
                      GINT_TO_POINTER(1));
  gtk_signal_connect (GTK_OBJECT (stoptactic_button), "clicked",
                      GTK_SIGNAL_FUNC (on_tactic_button_clicked),
                      GINT_TO_POINTER(0));
  gtk_signal_connect (GTK_OBJECT (gameinfo_button), "clicked",
                      GTK_SIGNAL_FUNC (on_gameinfo_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (on_set_button_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button18), "clicked",
                      GTK_SIGNAL_FUNC (on_refbox_ctrl_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button19), "clicked",
                      GTK_SIGNAL_FUNC (on_drive_ctrl_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button49), "clicked",
                      GTK_SIGNAL_FUNC (on_graph_ctrl_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (toolbar1), "realize",
                      GTK_SIGNAL_FUNC (OnDebugToolbarRealize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (checkbutton2), "toggled",
                      GTK_SIGNAL_FUNC (OnDebugToolBarClicked),
                      (gpointer) 1);
  gtk_signal_connect (GTK_OBJECT (checkbutton3), "toggled",
                      GTK_SIGNAL_FUNC (OnDebugToolBarClicked),
                      (gpointer) 2);
  gtk_signal_connect (GTK_OBJECT (checkbutton4), "toggled",
                      GTK_SIGNAL_FUNC (OnDebugToolBarClicked),
                      (gpointer) 4);
  gtk_signal_connect (GTK_OBJECT (checkbutton5), "toggled",
                      GTK_SIGNAL_FUNC (OnDebugToolBarClicked),
                      (gpointer) 8);
  gtk_signal_connect (GTK_OBJECT (checkbutton6), "toggled",
                      GTK_SIGNAL_FUNC (OnDebugToolBarClicked),
                      (gpointer) 0x10);
  gtk_signal_connect (GTK_OBJECT (checkbutton7), "toggled",
                      GTK_SIGNAL_FUNC (OnDebugToolBarClicked),
                      (gpointer) 0x20);
  gtk_signal_connect (GTK_OBJECT (darea), "configure_event",
                      GTK_SIGNAL_FUNC (on_darea_configure_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (darea), "expose_event",
                      GTK_SIGNAL_FUNC (on_darea_expose_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (darea), "motion_notify_event",
                      GTK_SIGNAL_FUNC (on_darea_motion_notify_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (darea), "button_press_event",
                      GTK_SIGNAL_FUNC (on_darea_button_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (darea), "button_release_event",
                      GTK_SIGNAL_FUNC (on_darea_button_release_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (darea), "key_press_event",
                      GTK_SIGNAL_FUNC (on_darea_key_press_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (SetCtrlBox), "realize",
                      GTK_SIGNAL_FUNC (on_SetCtrlBox_realize),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (on_enable_set_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button45), "clicked",
                      GTK_SIGNAL_FUNC (on_ball_graph_clicked),
                      (gpointer) 0);
  gtk_signal_connect (GTK_OBJECT (button46), "clicked",
                      GTK_SIGNAL_FUNC (on_ball_graph_clicked),
                      (gpointer) 1);
  gtk_signal_connect (GTK_OBJECT (button22), "clicked",
                      GTK_SIGNAL_FUNC (on_blue_graph_clicked),
                      (gpointer) 0);
  gtk_signal_connect (GTK_OBJECT (button23), "clicked",
                      GTK_SIGNAL_FUNC (on_blue_graph_clicked),
                      (gpointer) 1);
  gtk_signal_connect (GTK_OBJECT (button24), "clicked",
                      GTK_SIGNAL_FUNC (on_blue_graph_clicked),
                      (gpointer) 2);
  gtk_signal_connect (GTK_OBJECT (button40), "clicked",
                      GTK_SIGNAL_FUNC (on_blue_graph_clicked),
                      (gpointer) 3);
  gtk_signal_connect (GTK_OBJECT (button26), "clicked",
                      GTK_SIGNAL_FUNC (on_blue_graph_clicked),
                      (gpointer) 4);
  gtk_signal_connect (GTK_OBJECT (button31), "clicked",
                      GTK_SIGNAL_FUNC (on_yellow_graph_clicked),
                      (gpointer) 0);
  gtk_signal_connect (GTK_OBJECT (button41), "clicked",
                      GTK_SIGNAL_FUNC (on_yellow_graph_clicked),
                      (gpointer) 1);
  gtk_signal_connect (GTK_OBJECT (button42), "clicked",
                      GTK_SIGNAL_FUNC (on_yellow_graph_clicked),
                      (gpointer) 2);
  gtk_signal_connect (GTK_OBJECT (button43), "clicked",
                      GTK_SIGNAL_FUNC (on_yellow_graph_clicked),
                      (gpointer) 3);
  gtk_signal_connect (GTK_OBJECT (button44), "clicked",
                      GTK_SIGNAL_FUNC (on_yellow_graph_clicked),
                      (gpointer) 4);

  gtk_widget_grab_focus (darea);
  gtk_object_set_data (GTK_OBJECT (mainwin), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (mainwin), accel_group);

  return mainwin;
}

GtkWidget*
create_robotdlg (void)
{
  GtkWidget *robotdlg;
  GtkWidget *vbox2;
  GtkWidget *scrolledwindow1;
  GtkWidget *robottext;
  GtkWidget *rdlg_closebutton;

  robotdlg = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (robotdlg), "robotdlg", robotdlg);
  gtk_window_set_title (GTK_WINDOW (robotdlg), "RobotDialog");

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (robotdlg), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (robotdlg), vbox2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (robotdlg), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  robottext = gtk_text_new (NULL, NULL);
  gtk_widget_ref (robottext);
  gtk_object_set_data_full (GTK_OBJECT (robotdlg), "robottext", robottext,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (robottext);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), robottext);
  gtk_widget_set_usize (robottext, 500, 300);

  rdlg_closebutton = gtk_button_new_with_label ("Close");
  gtk_widget_ref (rdlg_closebutton);
  gtk_object_set_data_full (GTK_OBJECT (robotdlg), "rdlg_closebutton", rdlg_closebutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (rdlg_closebutton);
  gtk_box_pack_start (GTK_BOX (vbox2), rdlg_closebutton, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (robotdlg), "destroy",
                      GTK_SIGNAL_FUNC (on_robotdlg_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (rdlg_closebutton), "clicked",
                      GTK_SIGNAL_FUNC (on_robotdlg_close_clicked),
                      NULL);

  return robotdlg;
}

GtkWidget*
create_menu1 (void)
{
  GtkWidget *menu1;
  GtkAccelGroup *menu1_accels;

  menu1 = gtk_menu_new ();
  gtk_object_set_data (GTK_OBJECT (menu1), "menu1", menu1);
  menu1_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (menu1));

  return menu1;
}

GtkWidget*
create_aboutdlg (void)
{
  GtkWidget *aboutdlg;
  GtkWidget *scrolledwindow4;
  GtkWidget *viewport1;
  GtkWidget *vbox3;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *button4;

  aboutdlg = gtk_window_new (GTK_WINDOW_DIALOG);
  gtk_object_set_data (GTK_OBJECT (aboutdlg), "aboutdlg", aboutdlg);
  gtk_window_set_title (GTK_WINDOW (aboutdlg), "CMDragons About");
  gtk_window_set_default_size (GTK_WINDOW (aboutdlg), 312, 123);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (aboutdlg), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_container_add (GTK_CONTAINER (aboutdlg), scrolledwindow4);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow4), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (aboutdlg), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), viewport1);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (aboutdlg), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (viewport1), vbox3);

  label17 = gtk_label_new ("CM Dragons'02 GUI");
  gtk_widget_ref (label17);
  gtk_object_set_data_full (GTK_OBJECT (aboutdlg), "label17", label17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (vbox3), label17, FALSE, FALSE, 0);

  label18 = gtk_label_new ("Version 2.0");
  gtk_widget_ref (label18);
  gtk_object_set_data_full (GTK_OBJECT (aboutdlg), "label18", label18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (vbox3), label18, FALSE, FALSE, 0);

  label19 = gtk_label_new ("(c) Carnegie Mellon University, 2002");
  gtk_widget_ref (label19);
  gtk_object_set_data_full (GTK_OBJECT (aboutdlg), "label19", label19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (vbox3), label19, FALSE, FALSE, 0);

  button4 = gtk_button_new_with_label ("OK");
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (aboutdlg), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  gtk_box_pack_start (GTK_BOX (vbox3), button4, TRUE, TRUE, 0);

  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (on_aboutdlg_ok),
                      NULL);

  return aboutdlg;
}

GtkWidget*
create_refbox (void)
{
  GtkWidget *refbox;
  GtkWidget *vbox4;
  GtkWidget *hbuttonbox5;
  GtkWidget *button13;
  GtkWidget *button14;
  GtkWidget *scrolledwindow5;
  GtkWidget *text1;
  GtkWidget *hbuttonbox6;
  GtkWidget *button16;
  GtkWidget *button17;
  GtkWidget *hbuttonbox4;
  GtkWidget *button12;
  GtkWidget *hbuttonbox3;
  GtkWidget *button10;
  GtkWidget *button11;
  GtkWidget *table3;
  GtkWidget *label21;
  GtkWidget *label23;
  GSList *table3_group = NULL;
  GtkWidget *RBPenaltyblue;
  GtkWidget *RBKickoffyellow;
  GtkWidget *RBPenaltyyellow;
  GtkWidget *RBRestart;
  GtkWidget *RBKickoffblue;
  GtkWidget *label20;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label22;
  GtkWidget *RBFreekickyellow;
  GtkWidget *RBFreekickblue;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  refbox = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (refbox), "refbox", refbox);
  gtk_container_set_border_width (GTK_CONTAINER (refbox), 3);
  gtk_tooltips_set_tip (tooltips, refbox, "Simulated Referee Box", NULL);
  gtk_window_set_title (GTK_WINDOW (refbox), "SimReferee Box");
  gtk_window_set_policy (GTK_WINDOW (refbox), FALSE, FALSE, FALSE);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (refbox), vbox4);

  hbuttonbox5 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox5);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "hbuttonbox5", hbuttonbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox5);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox5, TRUE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox5), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox5), 100, 50);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox5), 2, 0);

  button13 = gtk_button_new_with_label ("Start");
  gtk_widget_ref (button13);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "button13", button13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button13);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button13);
  GTK_WIDGET_SET_FLAGS (button13, GTK_CAN_DEFAULT);

  button14 = gtk_button_new_with_label ("Stop");
  gtk_widget_ref (button14);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "button14", button14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button14);
  gtk_container_add (GTK_CONTAINER (hbuttonbox5), button14);
  GTK_WIDGET_SET_FLAGS (button14, GTK_CAN_DEFAULT);

  scrolledwindow5 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow5);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "scrolledwindow5", scrolledwindow5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow5);
  gtk_box_pack_start (GTK_BOX (vbox4), scrolledwindow5, TRUE, TRUE, 0);
  gtk_widget_set_usize (scrolledwindow5, -2, 88);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow5), GTK_POLICY_NEVER, GTK_POLICY_NEVER);

  text1 = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text1);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "text1", text1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow5), text1);
  gtk_widget_set_usize (text1, -2, 70);

  hbuttonbox6 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox6);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "hbuttonbox6", hbuttonbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox6);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox6, FALSE, FALSE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox6), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox6), 100, 50);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox6), 2, 0);

  button16 = gtk_button_new_with_label ("Timeout Yellow");
  gtk_widget_ref (button16);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "button16", button16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button16);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), button16);
  GTK_WIDGET_SET_FLAGS (button16, GTK_CAN_DEFAULT);

  button17 = gtk_button_new_with_label ("Timeout Blue");
  gtk_widget_ref (button17);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "button17", button17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button17);
  gtk_container_add (GTK_CONTAINER (hbuttonbox6), button17);
  GTK_WIDGET_SET_FLAGS (button17, GTK_CAN_DEFAULT);

  hbuttonbox4 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox4);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "hbuttonbox4", hbuttonbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox4);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox4, FALSE, FALSE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox4), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox4), 202, 50);

  button12 = gtk_button_new_with_label ("Stop Timeout");
  gtk_widget_ref (button12);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "button12", button12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button12);
  gtk_container_add (GTK_CONTAINER (hbuttonbox4), button12);
  GTK_WIDGET_SET_FLAGS (button12, GTK_CAN_DEFAULT);

  hbuttonbox3 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox3);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "hbuttonbox3", hbuttonbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox3);
  gtk_box_pack_start (GTK_BOX (vbox4), hbuttonbox3, TRUE, TRUE, 0);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox3), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox3), 100, 50);
  gtk_button_box_set_child_ipadding (GTK_BUTTON_BOX (hbuttonbox3), 2, 0);

  button10 = gtk_button_new_with_label ("Goal Yellow");
  gtk_widget_ref (button10);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "button10", button10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button10);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button10);
  GTK_WIDGET_SET_FLAGS (button10, GTK_CAN_DEFAULT);

  button11 = gtk_button_new_with_label ("Goal Blue");
  gtk_widget_ref (button11);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "button11", button11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button11);
  gtk_container_add (GTK_CONTAINER (hbuttonbox3), button11);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);

  table3 = gtk_table_new (5, 3, FALSE);
  gtk_widget_ref (table3);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "table3", table3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (table3);
  gtk_box_pack_start (GTK_BOX (vbox4), table3, TRUE, TRUE, 0);

  label21 = gtk_label_new ("Penalty");
  gtk_widget_ref (label21);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "label21", label21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table3), label21, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label23 = gtk_label_new ("Restart");
  gtk_widget_ref (label23);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "label23", label23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table3), label23, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label23), 0, 0.5);

  RBPenaltyblue = gtk_radio_button_new_with_label (table3_group, "");
  table3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (RBPenaltyblue));
  gtk_widget_ref (RBPenaltyblue);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "RBPenaltyblue", RBPenaltyblue,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RBPenaltyblue);
  gtk_table_attach (GTK_TABLE (table3), RBPenaltyblue, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  RBKickoffyellow = gtk_radio_button_new_with_label (table3_group, "");
  table3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (RBKickoffyellow));
  gtk_widget_ref (RBKickoffyellow);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "RBKickoffyellow", RBKickoffyellow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RBKickoffyellow);
  gtk_table_attach (GTK_TABLE (table3), RBKickoffyellow, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  RBPenaltyyellow = gtk_radio_button_new_with_label (table3_group, "");
  table3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (RBPenaltyyellow));
  gtk_widget_ref (RBPenaltyyellow);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "RBPenaltyyellow", RBPenaltyyellow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RBPenaltyyellow);
  gtk_table_attach (GTK_TABLE (table3), RBPenaltyyellow, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  RBRestart = gtk_radio_button_new_with_label (table3_group, "");
  table3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (RBRestart));
  gtk_widget_ref (RBRestart);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "RBRestart", RBRestart,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RBRestart);
  gtk_table_attach (GTK_TABLE (table3), RBRestart, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  RBKickoffblue = gtk_radio_button_new_with_label (table3_group, "");
  table3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (RBKickoffblue));
  gtk_widget_ref (RBKickoffblue);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "RBKickoffblue", RBKickoffblue,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RBKickoffblue);
  gtk_table_attach (GTK_TABLE (table3), RBKickoffblue, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label20 = gtk_label_new ("Kick off");
  gtk_widget_ref (label20);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "label20", label20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table3), label20, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label24 = gtk_label_new ("Blue");
  gtk_widget_ref (label24);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "label24", label24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table3), label24, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  label25 = gtk_label_new ("Yellow");
  gtk_widget_ref (label25);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "label25", label25,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table3), label25, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  label22 = gtk_label_new ("Free Kick");
  gtk_widget_ref (label22);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "label22", label22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table3), label22, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  RBFreekickyellow = gtk_radio_button_new_with_label (table3_group, "");
  table3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (RBFreekickyellow));
  gtk_widget_ref (RBFreekickyellow);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "RBFreekickyellow", RBFreekickyellow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RBFreekickyellow);
  gtk_table_attach (GTK_TABLE (table3), RBFreekickyellow, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  RBFreekickblue = gtk_radio_button_new_with_label (table3_group, "");
  table3_group = gtk_radio_button_group (GTK_RADIO_BUTTON (RBFreekickblue));
  gtk_widget_ref (RBFreekickblue);
  gtk_object_set_data_full (GTK_OBJECT (refbox), "RBFreekickblue", RBFreekickblue,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (RBFreekickblue);
  gtk_table_attach (GTK_TABLE (table3), RBFreekickblue, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  gtk_signal_connect (GTK_OBJECT (refbox), "configure_event",
                      GTK_SIGNAL_FUNC (on_refbox_configure_event),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (refbox), "destroy",
                      GTK_SIGNAL_FUNC (on_refbox_destroy),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button13), "clicked",
                      GTK_SIGNAL_FUNC (on_refbox_button_clicked),
                      GINT_TO_POINTER('s'));
  gtk_signal_connect (GTK_OBJECT (button14), "clicked",
                      GTK_SIGNAL_FUNC (on_refbox_button_clicked),
                      GINT_TO_POINTER('S'));
  gtk_signal_connect (GTK_OBJECT (button16), "clicked",
                      GTK_SIGNAL_FUNC (on_refbox_button_clicked),
                      GINT_TO_POINTER('t'));
  gtk_signal_connect (GTK_OBJECT (button17), "clicked",
                      GTK_SIGNAL_FUNC (on_refbox_button_clicked),
                      GINT_TO_POINTER('T'));
  gtk_signal_connect (GTK_OBJECT (button12), "clicked",
                      GTK_SIGNAL_FUNC (on_refbox_button_clicked),
                      GINT_TO_POINTER('z'));
  gtk_signal_connect (GTK_OBJECT (button10), "clicked",
                      GTK_SIGNAL_FUNC (on_refbox_button_clicked),
                      GINT_TO_POINTER('g'));
  gtk_signal_connect (GTK_OBJECT (button11), "clicked",
                      GTK_SIGNAL_FUNC (on_refbox_button_clicked),
                      GINT_TO_POINTER('G'));
  gtk_signal_connect (GTK_OBJECT (RBPenaltyblue), "toggled",
                      GTK_SIGNAL_FUNC (on_refbox_toggled),
                      GINT_TO_POINTER('P'));
  gtk_signal_connect (GTK_OBJECT (RBKickoffyellow), "toggled",
                      GTK_SIGNAL_FUNC (on_refbox_toggled),
                      GINT_TO_POINTER('k'));
  gtk_signal_connect (GTK_OBJECT (RBPenaltyyellow), "toggled",
                      GTK_SIGNAL_FUNC (on_refbox_toggled),
                      GINT_TO_POINTER('p'));
  gtk_signal_connect (GTK_OBJECT (RBRestart), "toggled",
                      GTK_SIGNAL_FUNC (on_refbox_toggled),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (RBKickoffblue), "toggled",
                      GTK_SIGNAL_FUNC (on_refbox_toggled),
                      GINT_TO_POINTER('K'));
  gtk_signal_connect (GTK_OBJECT (RBFreekickyellow), "toggled",
                      GTK_SIGNAL_FUNC (on_refbox_toggled),
                      GINT_TO_POINTER('f'));
  gtk_signal_connect (GTK_OBJECT (RBFreekickblue), "toggled",
                      GTK_SIGNAL_FUNC (on_refbox_toggled),
                      GINT_TO_POINTER('F'));

  gtk_object_set_data (GTK_OBJECT (refbox), "tooltips", tooltips);

  return refbox;
}

GtkWidget*
create_graph_display (void)
{
  GtkWidget *graph_display;
  GtkWidget *vbox5;
  GtkWidget *graph_drawarea;
  GtkWidget *hbuttonbox7;
  GtkWidget *GraphUpdate;
  GtkWidget *GraphClose;

  graph_display = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (graph_display), "graph_display", graph_display);
  gtk_window_set_title (GTK_WINDOW (graph_display), "Graph Display");

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (graph_display), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (graph_display), vbox5);

  graph_drawarea = gtk_drawing_area_new ();
  gtk_widget_ref (graph_drawarea);
  gtk_object_set_data_full (GTK_OBJECT (graph_display), "graph_drawarea", graph_drawarea,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (graph_drawarea);
  gtk_box_pack_start (GTK_BOX (vbox5), graph_drawarea, TRUE, TRUE, 0);
  gtk_widget_set_usize (graph_drawarea, 554, 274);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_ref (hbuttonbox7);
  gtk_object_set_data_full (GTK_OBJECT (graph_display), "hbuttonbox7", hbuttonbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbuttonbox7);
  gtk_box_pack_start (GTK_BOX (vbox5), hbuttonbox7, FALSE, TRUE, 0);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox7), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox7), 0);
  gtk_button_box_set_child_size (GTK_BUTTON_BOX (hbuttonbox7), 93, 27);

  GraphUpdate = gtk_button_new_with_label ("Update");
  gtk_widget_ref (GraphUpdate);
  gtk_object_set_data_full (GTK_OBJECT (graph_display), "GraphUpdate", GraphUpdate,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GraphUpdate);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), GraphUpdate);
  GTK_WIDGET_SET_FLAGS (GraphUpdate, GTK_CAN_DEFAULT);

  GraphClose = gtk_button_new_with_label ("Close");
  gtk_widget_ref (GraphClose);
  gtk_object_set_data_full (GTK_OBJECT (graph_display), "GraphClose", GraphClose,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (GraphClose);
  gtk_container_add (GTK_CONTAINER (hbuttonbox7), GraphClose);
  GTK_WIDGET_SET_FLAGS (GraphClose, GTK_CAN_DEFAULT);

  return graph_display;
}

