/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwin (void);
GtkWidget* create_robotdlg (void);
GtkWidget* create_menu1 (void);
GtkWidget* create_aboutdlg (void);
GtkWidget* create_refbox (void);
GtkWidget* create_graph_display (void);
