/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_cmveditor (void);
GtkWidget* create_colormapwin (void);
GtkWidget* create_display (void);
GtkWidget* create_window1 (void);
